const fs = require('fs');
const path = require('path');

const b01 = [
  {name:"apricot",category:"fruit",taste:"sweet sour",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"apricot brandy",category:"spirit",taste:"sweet pungent",cuisines:["French","Hungarian"],isJunk:false,junkReason:""},
  {name:"apricot gelatin",category:"condiment",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"apricot halve",category:"fruit",taste:"sweet sour",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"apricot jam",category:"condiment",taste:"sweet",cuisines:["French","British","Moroccan"],isJunk:false,junkReason:""},
  {name:"apricot jello",category:"condiment",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"apricot jelly",category:"condiment",taste:"sweet",cuisines:["French","British"],isJunk:false,junkReason:""},
  {name:"apricot juice",category:"liquid",taste:"sweet sour",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"apricot nectar",category:"liquid",taste:"sweet sour",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"apricot pie filling",category:"condiment",taste:"sweet sour",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"apricot preserve",category:"condiment",taste:"sweet",cuisines:["French","British","Moroccan"],isJunk:false,junkReason:""},
  {name:"arar",category:"other",taste:"bitter astringent",cuisines:["Lebanese","Moroccan"],isJunk:false,junkReason:""},
  {name:"arbol chile",category:"chili",taste:"spicy pungent",cuisines:["Mexican","Tex-Mex"],isJunk:false,junkReason:""},
  {name:"armour beef",category:"protein",taste:"umami salty",cuisines:["American"],isJunk:true,junkReason:"Branded product (Armour is a commercial meat brand)"},
  {name:"arrowhead",category:"vegetable",taste:"sweet",cuisines:["Chinese","Japanese"],isJunk:false,junkReason:""},
  {name:"arrowroot",category:"thickener",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"arrowroot flour",category:"thickener",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"arrowroot powder",category:"thickener",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"arrowroot starch",category:"thickener",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"artemisia",category:"herb",taste:"bitter pungent",cuisines:["Chinese","Persian","Moroccan"],isJunk:false,junkReason:""},
  {name:"artichoke",category:"vegetable",taste:"bitter sweet",cuisines:["Italian","French","Spanish","Lebanese"],isJunk:false,junkReason:""},
  {name:"asadero cheese",category:"dairy",taste:"salty umami",cuisines:["Mexican"],isJunk:false,junkReason:""},
  {name:"asafoetida",category:"spice",taste:"pungent",cuisines:["Indian","Pakistani","Persian"],isJunk:false,junkReason:""},
  {name:"asafoetida powder",category:"spice",taste:"pungent",cuisines:["Indian","Pakistani","Persian"],isJunk:false,junkReason:""},
  {name:"ashgourd",category:"vegetable",taste:"sweet",cuisines:["Indian","Chinese","Sri Lankan"],isJunk:false,junkReason:""},
  {name:"asiago cheese",category:"dairy",taste:"salty umami",cuisines:["Italian"],isJunk:false,junkReason:""},
  {name:"asian chili paste",category:"condiment",taste:"spicy pungent",cuisines:["Chinese","Korean","Thai","Vietnamese"],isJunk:false,junkReason:""},
  {name:"asian chili sauce",category:"condiment",taste:"spicy pungent",cuisines:["Chinese","Thai","Vietnamese","Korean"],isJunk:false,junkReason:""},
  {name:"asian chili-garlic",category:"condiment",taste:"spicy pungent",cuisines:["Chinese","Thai","Vietnamese","Korean"],isJunk:false,junkReason:""},
  {name:"asian fish sauce",category:"umami",taste:"umami salty pungent",cuisines:["Thai","Vietnamese","Filipino","Indonesian"],isJunk:false,junkReason:""},
  {name:"asian pear",category:"fruit",taste:"sweet",cuisines:["Chinese","Japanese","Korean"],isJunk:false,junkReason:""},
  {name:"asian sesame oil",category:"fat",taste:"pungent",cuisines:["Chinese","Japanese","Korean"],isJunk:false,junkReason:""},
  {name:"asparagus",category:"vegetable",taste:"bitter astringent",cuisines:["French","Italian","Chinese","American"],isJunk:false,junkReason:""},
  {name:"atlantic halibut",category:"protein",taste:"umami",cuisines:["American","Scandinavian","British"],isJunk:false,junkReason:""},
  {name:"atlantic herring",category:"protein",taste:"umami salty",cuisines:["Scandinavian","British","Russian","Polish"],isJunk:false,junkReason:""},
  {name:"avocado",category:"fruit",taste:"sweet",cuisines:["Mexican","Peruvian","Caribbean"],isJunk:false,junkReason:""},
  {name:"avocado dip",category:"condiment",taste:"sweet pungent",cuisines:["Mexican","Tex-Mex"],isJunk:false,junkReason:""},
  {name:"avocado oil",category:"fat",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"avocado salsa",category:"condiment",taste:"spicy sour pungent",cuisines:["Mexican","Tex-Mex"],isJunk:false,junkReason:""},
  {name:"avocadoe",category:"fruit",taste:"sweet",cuisines:["Mexican","Peruvian","Caribbean"],isJunk:false,junkReason:""},
  {name:"babaco",category:"fruit",taste:"sour sweet",cuisines:["Peruvian","Brazilian"],isJunk:false,junkReason:""},
  {name:"babassu palm",category:"fat",taste:"sweet",cuisines:["Brazilian"],isJunk:false,junkReason:""},
  {name:"baby back pork ribs",category:"protein",taste:"umami salty",cuisines:["American","Chinese","Korean"],isJunk:false,junkReason:""},
  {name:"baby bella mushroom",category:"vegetable",taste:"umami",cuisines:["Italian","American","Chinese","Japanese"],isJunk:false,junkReason:""},
  {name:"baby carrot",category:"vegetable",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"baby clam",category:"protein",taste:"umami salty",cuisines:["Italian","Japanese","Portuguese"],isJunk:false,junkReason:""},
  {name:"baby corn",category:"vegetable",taste:"sweet",cuisines:["Chinese","Thai","Vietnamese"],isJunk:false,junkReason:""},
  {name:"baby eggplant",category:"vegetable",taste:"bitter astringent",cuisines:["Italian","Indian","Turkish","Japanese"],isJunk:false,junkReason:""},
  {name:"baby lettuce",category:"vegetable",taste:"bitter astringent",cuisines:["American","French"],isJunk:false,junkReason:""},
  {name:"baby lima bean",category:"protein",taste:"sweet astringent",cuisines:["American","Southern US"],isJunk:false,junkReason:""},
  {name:"baby new potatoe",category:"vegetable",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"baby onion",category:"aromatic",taste:"pungent sweet",cuisines:["French","Italian","British"],isJunk:false,junkReason:""},
  {name:"baby pea",category:"vegetable",taste:"sweet",cuisines:["British","French"],isJunk:false,junkReason:""},
  {name:"baby portabella mushroom",category:"vegetable",taste:"umami",cuisines:["Italian","American"],isJunk:false,junkReason:""},
  {name:"baby portobello mushroom",category:"vegetable",taste:"umami",cuisines:["Italian","American"],isJunk:false,junkReason:""},
  {name:"baby potatoe",category:"vegetable",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"baby red potatoe",category:"vegetable",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"baby romaine lettuce",category:"vegetable",taste:"bitter astringent",cuisines:["American","Italian"],isJunk:false,junkReason:""},
  {name:"baby shrimp",category:"protein",taste:"umami salty",cuisines:["Cajun/Creole","Thai","Vietnamese","Chinese"],isJunk:false,junkReason:""},
  {name:"baby spinach",category:"vegetable",taste:"bitter astringent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"baby spinach leave",category:"vegetable",taste:"bitter astringent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"back bacon",category:"protein",taste:"salty umami",cuisines:["British","Canadian"],isJunk:false,junkReason:""},
  {name:"backfin crabmeat",category:"protein",taste:"umami salty",cuisines:["American","Cajun/Creole"],isJunk:false,junkReason:""},
  {name:"bacon",category:"protein",taste:"salty umami",cuisines:["American","British","German"],isJunk:false,junkReason:""},
  {name:"bacon bit",category:"protein",taste:"salty umami",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"bacon dripping",category:"fat",taste:"salty umami",cuisines:["British","Southern US"],isJunk:false,junkReason:""},
  {name:"bacon fat",category:"fat",taste:"salty umami",cuisines:["American","British","Southern US"],isJunk:false,junkReason:""},
  {name:"bacon grease",category:"fat",taste:"salty umami",cuisines:["American","British","Southern US"],isJunk:false,junkReason:""},
  {name:"bacon lardon",category:"protein",taste:"salty umami",cuisines:["French"],isJunk:false,junkReason:""},
  {name:"bacon rasher",category:"protein",taste:"salty umami",cuisines:["British","Irish"],isJunk:false,junkReason:""},
  {name:"bacon strip",category:"protein",taste:"salty umami",cuisines:["American","British"],isJunk:false,junkReason:""},
  {name:"bags spinach",category:"vegetable",taste:"bitter astringent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bailey's irish cream",category:"liqueur",taste:"sweet",cuisines:["British"],isJunk:false,junkReason:""},
  {name:"baileys irish cream",category:"liqueur",taste:"sweet",cuisines:["British"],isJunk:false,junkReason:""},
  {name:"baked potato",category:"vegetable",taste:"sweet",cuisines:["American","British"],isJunk:true,junkReason:"Prepared dish, not a raw ingredient"},
  {name:"baking apple",category:"fruit",taste:"sour sweet",cuisines:["American","British"],isJunk:false,junkReason:""},
  {name:"baking bit",category:"confection",taste:"sweet bitter",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"baking chip",category:"confection",taste:"sweet bitter",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"baking chocolate",category:"confection",taste:"bitter",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"baking cocoa",category:"condiment",taste:"bitter",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"baking crumb",category:"grain",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"baking flour",category:"grain",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"baking hen",category:"protein",taste:"umami",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"baking mix",category:"grain",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"baking potato",category:"vegetable",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"baking potatoe",category:"vegetable",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"baking square",category:"confection",taste:"bitter",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"balsalmic vinegar",category:"acid",taste:"sour sweet",cuisines:["Italian"],isJunk:false,junkReason:""},
  {name:"balsamic dressing",category:"condiment",taste:"sour sweet",cuisines:["Italian"],isJunk:false,junkReason:""},
  {name:"balsamic glaze",category:"condiment",taste:"sweet sour",cuisines:["Italian"],isJunk:false,junkReason:""},
  {name:"balsamic vinegar",category:"acid",taste:"sour sweet",cuisines:["Italian"],isJunk:false,junkReason:""},
  {name:"bamboo shoot",category:"vegetable",taste:"sweet astringent",cuisines:["Chinese","Japanese","Vietnamese","Thai"],isJunk:false,junkReason:""},
  {name:"banana",category:"fruit",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"banana chip",category:"confection",taste:"sweet",cuisines:["Caribbean","Filipino"],isJunk:false,junkReason:""},
  {name:"banana cream",category:"condiment",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"banana flavoring",category:"condiment",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"banana instant pudding",category:"condiment",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"banana leaf",category:"other",taste:"astringent",cuisines:["Filipino","Thai","Indian","Caribbean"],isJunk:false,junkReason:""},
  {name:"banana liqueur",category:"liqueur",taste:"sweet",cuisines:["Caribbean"],isJunk:false,junkReason:""},
  {name:"banana mashed",category:"fruit",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""}
];

const b02 = [
  {name:"banana pepper",category:"chili",taste:"spicy sweet",cuisines:["American","Italian","Mexican"],isJunk:false,junkReason:""},
  {name:"bananas mashed",category:"fruit",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"barbecue beef",category:"protein",taste:"umami salty",cuisines:["American","Korean"],isJunk:false,junkReason:""},
  {name:"barbecue pork",category:"protein",taste:"umami salty",cuisines:["American","Chinese","Korean"],isJunk:false,junkReason:""},
  {name:"barbecue sauce",category:"condiment",taste:"sweet sour spicy",cuisines:["American","Southern US"],isJunk:false,junkReason:""},
  {name:"barbecued pork",category:"protein",taste:"umami salty",cuisines:["Chinese","American"],isJunk:false,junkReason:""},
  {name:"barbeque sauce",category:"condiment",taste:"sweet sour spicy",cuisines:["American","Southern US"],isJunk:false,junkReason:""},
  {name:"barbq sauce",category:"condiment",taste:"sweet sour spicy",cuisines:["American","Southern US"],isJunk:false,junkReason:""},
  {name:"barley",category:"grain",taste:"sweet",cuisines:["British","German","Middle Eastern"],isJunk:false,junkReason:""},
  {name:"barley flour",category:"grain",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"barley malt",category:"grain",taste:"sweet",cuisines:["British","German"],isJunk:false,junkReason:""},
  {name:"barley malt syrup",category:"sweetener",taste:"sweet",cuisines:["British","German"],isJunk:false,junkReason:""},
  {name:"barrel cheese",category:"dairy",taste:"salty umami",cuisines:["Polish","German"],isJunk:false,junkReason:""},
  {name:"bartlett pear",category:"fruit",taste:"sweet",cuisines:["American","French"],isJunk:false,junkReason:""},
  {name:"basil",category:"herb",taste:"sweet pungent",cuisines:["Italian","Thai","Vietnamese"],isJunk:false,junkReason:""},
  {name:"basil chiffonade",category:"herb",taste:"sweet pungent",cuisines:["Italian","French"],isJunk:false,junkReason:""},
  {name:"basil freshly",category:"herb",taste:"sweet pungent",cuisines:["Italian","Thai"],isJunk:false,junkReason:""},
  {name:"basil leaf",category:"herb",taste:"sweet pungent",cuisines:["Italian","Thai","Vietnamese"],isJunk:false,junkReason:""},
  {name:"basil oil",category:"fat",taste:"sweet pungent",cuisines:["Italian","French"],isJunk:false,junkReason:""},
  {name:"basil pesto",category:"condiment",taste:"sweet pungent",cuisines:["Italian"],isJunk:false,junkReason:""},
  {name:"basket cherry tomatoe",category:"vegetable",taste:"sweet sour",cuisines:["Italian","Spanish","American"],isJunk:false,junkReason:""},
  {name:"basting sauce",category:"condiment",taste:"sweet salty umami",cuisines:["American","Chinese","Korean"],isJunk:false,junkReason:""},
  {name:"bay leaf",category:"herb",taste:"bitter pungent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bay leaf powder",category:"herb",taste:"bitter pungent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bay scallop",category:"protein",taste:"umami sweet",cuisines:["American","French","Japanese"],isJunk:false,junkReason:""},
  {name:"bay shrimp",category:"protein",taste:"umami salty",cuisines:["American","Cajun/Creole"],isJunk:false,junkReason:""},
  {name:"bayberry",category:"fruit",taste:"sour astringent",cuisines:["Chinese","American"],isJunk:false,junkReason:""},
  {name:"bayleaf",category:"herb",taste:"bitter pungent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bbq sauce",category:"condiment",taste:"sweet sour spicy",cuisines:["American","Southern US"],isJunk:false,junkReason:""},
  {name:"bean",category:"protein",taste:"sweet astringent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bean curd",category:"protein",taste:"sweet umami",cuisines:["Chinese","Japanese","Korean","Vietnamese"],isJunk:false,junkReason:""},
  {name:"bean dip",category:"condiment",taste:"sweet salty",cuisines:["Mexican","Tex-Mex"],isJunk:false,junkReason:""},
  {name:"bean paste",category:"condiment",taste:"sweet umami",cuisines:["Chinese","Japanese","Korean"],isJunk:false,junkReason:""},
  {name:"bean sauce",category:"condiment",taste:"umami salty",cuisines:["Chinese","Korean","Vietnamese"],isJunk:false,junkReason:""},
  {name:"bean soup mix",category:"protein",taste:"sweet umami",cuisines:["American","Italian"],isJunk:false,junkReason:""},
  {name:"bean sprout",category:"vegetable",taste:"sweet astringent",cuisines:["Chinese","Vietnamese","Thai","Korean"],isJunk:false,junkReason:""},
  {name:"bean thread",category:"grain",taste:"sweet",cuisines:["Chinese","Vietnamese","Thai","Korean"],isJunk:false,junkReason:""},
  {name:"bean with bacon soup",category:"condiment",taste:"umami salty",cuisines:["American"],isJunk:true,junkReason:"Prepared compound soup product, not a single ingredient"},
  {name:"bearnaise sauce",category:"condiment",taste:"sour sweet umami",cuisines:["French"],isJunk:false,junkReason:""},
  {name:"beaten egg",category:"protein",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bechamel",category:"condiment",taste:"sweet salty",cuisines:["French","Italian","Greek"],isJunk:false,junkReason:""},
  {name:"bechamel sauce",category:"condiment",taste:"sweet salty",cuisines:["French","Italian","Greek"],isJunk:false,junkReason:""},
  {name:"beech nut",category:"nut",taste:"sweet astringent",cuisines:["German","French"],isJunk:false,junkReason:""},
  {name:"beef",category:"protein",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"beef base",category:"umami",taste:"umami salty",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"beef bone",category:"protein",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"beef bouillon",category:"umami",taste:"umami salty",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"beef bouillon cube",category:"umami",taste:"umami salty",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"beef bouillon granule",category:"umami",taste:"umami salty",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"beef bouillon powder",category:"umami",taste:"umami salty",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"beef bouillon soup",category:"liquid",taste:"umami salty",cuisines:["French","British"],isJunk:false,junkReason:""},
  {name:"beef brisket",category:"protein",taste:"umami salty",cuisines:["American","Jewish","Korean"],isJunk:false,junkReason:""},
  {name:"beef chuck",category:"protein",taste:"umami",cuisines:["American","Argentine"],isJunk:false,junkReason:""},
  {name:"beef chuck roast",category:"protein",taste:"umami",cuisines:["American","Argentine"],isJunk:false,junkReason:""},
  {name:"beef chuck steak",category:"protein",taste:"umami",cuisines:["American","Argentine"],isJunk:false,junkReason:""},
  {name:"beef consomme",category:"liquid",taste:"umami salty",cuisines:["French"],isJunk:false,junkReason:""},
  {name:"beef cube",category:"protein",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"beef dripping",category:"fat",taste:"umami salty",cuisines:["British","Argentine"],isJunk:false,junkReason:""},
  {name:"beef fillet",category:"protein",taste:"umami",cuisines:["Argentine","French","British"],isJunk:false,junkReason:""},
  {name:"beef flank",category:"protein",taste:"umami",cuisines:["Argentine","Korean","Mexican"],isJunk:false,junkReason:""},
  {name:"beef flank steak",category:"protein",taste:"umami",cuisines:["Argentine","Korean","Mexican"],isJunk:false,junkReason:""},
  {name:"beef flavor",category:"umami",taste:"umami salty",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"beef gravy",category:"condiment",taste:"umami salty",cuisines:["British","American"],isJunk:false,junkReason:""},
  {name:"beef lean",category:"protein",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"beef liver",category:"protein",taste:"umami bitter",cuisines:["Argentine","German","French"],isJunk:false,junkReason:""},
  {name:"beef mince",category:"protein",taste:"umami",cuisines:["British","Argentine","Italian"],isJunk:false,junkReason:""},
  {name:"beef pattie",category:"protein",taste:"umami salty",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"beef pot roast",category:"protein",taste:"umami salty",cuisines:["American"],isJunk:true,junkReason:"Prepared dish, not a raw ingredient"},
  {name:"beef rib",category:"protein",taste:"umami",cuisines:["Argentine","American","Korean"],isJunk:false,junkReason:""},
  {name:"beef roast",category:"protein",taste:"umami",cuisines:["American","British","Argentine"],isJunk:false,junkReason:""},
  {name:"beef round",category:"protein",taste:"umami",cuisines:["American","Argentine"],isJunk:false,junkReason:""},
  {name:"beef round steak",category:"protein",taste:"umami",cuisines:["American","Argentine"],isJunk:false,junkReason:""},
  {name:"beef rump",category:"protein",taste:"umami",cuisines:["Argentine","British","Australian"],isJunk:false,junkReason:""},
  {name:"beef rump roast",category:"protein",taste:"umami",cuisines:["American","Argentine"],isJunk:false,junkReason:""},
  {name:"beef sausage",category:"protein",taste:"salty umami",cuisines:["German","American","Argentine"],isJunk:false,junkReason:""},
  {name:"beef shank",category:"protein",taste:"umami",cuisines:["Argentine","Italian","Chinese"],isJunk:false,junkReason:""},
  {name:"beef short rib",category:"protein",taste:"umami",cuisines:["Argentine","Korean","American"],isJunk:false,junkReason:""},
  {name:"beef shoulder",category:"protein",taste:"umami",cuisines:["Argentine","American"],isJunk:false,junkReason:""},
  {name:"beef sirloin",category:"protein",taste:"umami",cuisines:["Argentine","American","British"],isJunk:false,junkReason:""},
  {name:"beef sirloin steak",category:"protein",taste:"umami",cuisines:["Argentine","American","British"],isJunk:false,junkReason:""},
  {name:"beef sirloin tip roast",category:"protein",taste:"umami",cuisines:["American","Argentine"],isJunk:false,junkReason:""},
  {name:"beef skirt",category:"protein",taste:"umami",cuisines:["Argentine","Mexican","American"],isJunk:false,junkReason:""},
  {name:"beef skirt steak",category:"protein",taste:"umami",cuisines:["Argentine","Mexican","American"],isJunk:false,junkReason:""},
  {name:"beef soup bone",category:"protein",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"beef steak",category:"protein",taste:"umami",cuisines:["Argentine","American","British"],isJunk:false,junkReason:""},
  {name:"beef stew",category:"protein",taste:"umami salty",cuisines:["American","French","Irish"],isJunk:true,junkReason:"Prepared dish, not a single ingredient"},
  {name:"beef stew meat",category:"protein",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"beef stew seasoning",category:"seasoning",taste:"salty pungent umami",cuisines:["American","French"],isJunk:false,junkReason:""},
  {name:"beef stock",category:"liquid",taste:"umami salty",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"beef strip",category:"protein",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"beef suet",category:"fat",taste:"umami",cuisines:["British"],isJunk:false,junkReason:""},
  {name:"beef tenderloin",category:"protein",taste:"umami",cuisines:["Argentine","American","French"],isJunk:false,junkReason:""},
  {name:"beef tip",category:"protein",taste:"umami",cuisines:["American","Argentine"],isJunk:false,junkReason:""},
  {name:"beef top sirloin",category:"protein",taste:"umami",cuisines:["Argentine","American"],isJunk:false,junkReason:""},
  {name:"beef tri",category:"protein",taste:"umami",cuisines:["American","Argentine"],isJunk:false,junkReason:""},
  {name:"beefeater",category:"spirit",taste:"bitter pungent",cuisines:["British"],isJunk:false,junkReason:""},
  {name:"beefsteak tomato",category:"vegetable",taste:"sweet sour umami",cuisines:["Italian","American","Spanish"],isJunk:false,junkReason:""},
  {name:"beefsteak tomatoe",category:"vegetable",taste:"sweet sour umami",cuisines:["Italian","American","Spanish"],isJunk:false,junkReason:""},
  {name:"beer",category:"liquid",taste:"bitter",cuisines:["German","British","Belgian"],isJunk:false,junkReason:""},
  {name:"beet",category:"vegetable",taste:"sweet",cuisines:["Russian","Scandinavian","Polish","German"],isJunk:false,junkReason:""}
];

const b03 = [
  {name:"beet juice",category:"liquid",taste:"sweet",cuisines:["Russian","Scandinavian","Polish"],isJunk:false,junkReason:""},
  {name:"beetroot",category:"vegetable",taste:"sweet",cuisines:["Russian","Scandinavian","British","Eastern European"],isJunk:false,junkReason:""},
  {name:"bella mushroom",category:"vegetable",taste:"umami",cuisines:["Italian","American"],isJunk:false,junkReason:""},
  {name:"benedictine",category:"liqueur",taste:"sweet bitter",cuisines:["French"],isJunk:false,junkReason:""},
  {name:"berbere",category:"seasoning",taste:"spicy pungent",cuisines:["Ethiopian"],isJunk:false,junkReason:""},
  {name:"bergamot",category:"citrus",taste:"sour bitter",cuisines:["Italian","Turkish"],isJunk:false,junkReason:""},
  {name:"bermuda onion",category:"aromatic",taste:"pungent sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"berry",category:"fruit",taste:"sweet sour",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bibb lettuce",category:"vegetable",taste:"bitter astringent",cuisines:["American","French"],isJunk:false,junkReason:""},
  {name:"bibb lettuce leave",category:"vegetable",taste:"bitter astringent",cuisines:["American","French"],isJunk:false,junkReason:""},
  {name:"bilberry",category:"fruit",taste:"sour sweet",cuisines:["Scandinavian","British"],isJunk:false,junkReason:""},
  {name:"bilberry wine",category:"liquid",taste:"sour sweet",cuisines:["Scandinavian","British"],isJunk:false,junkReason:""},
  {name:"biscuit",category:"baked",taste:"sweet",cuisines:["American","British"],isJunk:false,junkReason:""},
  {name:"biscuit baking",category:"baked",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"biscuit baking mix",category:"baked",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"biscuit crumb",category:"baked",taste:"sweet",cuisines:["British","American"],isJunk:false,junkReason:""},
  {name:"biscuit/baking",category:"baked",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"biscuit/baking mix",category:"baked",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"bison",category:"protein",taste:"umami",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"bitter chocolate",category:"confection",taste:"bitter",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bittergourd",category:"vegetable",taste:"bitter astringent",cuisines:["Indian","Chinese","Filipino","Thai"],isJunk:false,junkReason:""},
  {name:"bitters",category:"bitters",taste:"bitter",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bittersweet",category:"confection",taste:"bitter sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bittersweet chocolate chip",category:"confection",taste:"bitter sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"black bean",category:"protein",taste:"sweet umami",cuisines:["Mexican","Brazilian","Caribbean","Tex-Mex"],isJunk:false,junkReason:""},
  {name:"black bean garlic sauce",category:"condiment",taste:"umami salty pungent",cuisines:["Chinese"],isJunk:false,junkReason:""},
  {name:"black bean sauce",category:"condiment",taste:"umami salty",cuisines:["Chinese","Vietnamese"],isJunk:false,junkReason:""},
  {name:"black cardamom",category:"spice",taste:"pungent bitter",cuisines:["Indian","Pakistani","Chinese","Ethiopian"],isJunk:false,junkReason:""},
  {name:"black cardamom pod",category:"spice",taste:"pungent bitter",cuisines:["Indian","Pakistani","Chinese","Ethiopian"],isJunk:false,junkReason:""},
  {name:"black cherry",category:"fruit",taste:"sweet sour",cuisines:["French","German","American"],isJunk:false,junkReason:""},
  {name:"black cherry gelatin",category:"condiment",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"black cherry jello",category:"condiment",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"black cod",category:"protein",taste:"umami sweet",cuisines:["Japanese","American","Scandinavian"],isJunk:false,junkReason:""},
  {name:"black cumin",category:"spice",taste:"pungent bitter",cuisines:["Indian","Pakistani","Middle Eastern","Persian"],isJunk:false,junkReason:""},
  {name:"black grape",category:"fruit",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"black huckleberry",category:"fruit",taste:"sweet sour",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"black licorice",category:"confection",taste:"sweet pungent",cuisines:["Scandinavian","British","American"],isJunk:false,junkReason:""},
  {name:"black mushroom",category:"vegetable",taste:"umami",cuisines:["Chinese","Japanese","Korean"],isJunk:false,junkReason:""},
  {name:"black mustard seed",category:"spice",taste:"pungent bitter",cuisines:["Indian","Pakistani","Sri Lankan"],isJunk:false,junkReason:""},
  {name:"black olive",category:"vegetable",taste:"salty bitter",cuisines:["Italian","Greek","Spanish","Turkish","Lebanese"],isJunk:false,junkReason:""},
  {name:"black olive tapenade",category:"condiment",taste:"salty bitter umami",cuisines:["French","Italian","Greek"],isJunk:false,junkReason:""},
  {name:"black pepper",category:"spice",taste:"spicy pungent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"black peppercorn",category:"spice",taste:"spicy pungent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"black pitted olive",category:"vegetable",taste:"salty bitter",cuisines:["Italian","Greek","Spanish","Turkish"],isJunk:false,junkReason:""},
  {name:"black plum",category:"fruit",taste:"sweet sour",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"black pudding",category:"protein",taste:"salty umami",cuisines:["British","Irish"],isJunk:false,junkReason:""},
  {name:"black raisin",category:"fruit",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"black raspberry",category:"fruit",taste:"sweet sour",cuisines:["American","British"],isJunk:false,junkReason:""},
  {name:"black raspberry jello",category:"condiment",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"black rice",category:"grain",taste:"sweet",cuisines:["Chinese","Indonesian","Thai"],isJunk:false,junkReason:""},
  {name:"black salsify",category:"vegetable",taste:"sweet",cuisines:["Spanish","French","Belgian"],isJunk:false,junkReason:""},
  {name:"black salt",category:"seasoning",taste:"salty pungent",cuisines:["Indian","Pakistani"],isJunk:false,junkReason:""},
  {name:"black sambuca",category:"liqueur",taste:"sweet pungent",cuisines:["Italian"],isJunk:false,junkReason:""},
  {name:"black sesame",category:"nut",taste:"bitter sweet",cuisines:["Chinese","Japanese","Korean"],isJunk:false,junkReason:""},
  {name:"black sesame seed",category:"nut",taste:"bitter sweet",cuisines:["Chinese","Japanese","Korean"],isJunk:false,junkReason:""},
  {name:"black soy sauce",category:"umami",taste:"salty sweet umami",cuisines:["Chinese","Thai","Indonesian"],isJunk:false,junkReason:""},
  {name:"black tea",category:"liquid",taste:"bitter astringent",cuisines:["British","Indian","Chinese"],isJunk:false,junkReason:""},
  {name:"black treacle",category:"sweetener",taste:"sweet bitter",cuisines:["British"],isJunk:false,junkReason:""},
  {name:"black vinegar",category:"acid",taste:"sour sweet",cuisines:["Chinese","Japanese"],isJunk:false,junkReason:""},
  {name:"black walnut",category:"nut",taste:"bitter sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"black walnut flavoring",category:"condiment",taste:"sweet bitter",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"black-eyed pea",category:"protein",taste:"sweet umami",cuisines:["Southern US","West African","Caribbean","Indian"],isJunk:false,junkReason:""},
  {name:"blackberry",category:"fruit",taste:"sweet sour",cuisines:["American","British"],isJunk:false,junkReason:""},
  {name:"blackberry jam",category:"condiment",taste:"sweet",cuisines:["British","American"],isJunk:false,junkReason:""},
  {name:"blackberry jello",category:"condiment",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"blackberry preserve",category:"condiment",taste:"sweet",cuisines:["British","American"],isJunk:false,junkReason:""},
  {name:"blackberry wine",category:"liquid",taste:"sweet sour",cuisines:["British","American"],isJunk:false,junkReason:""},
  {name:"blackcurrant",category:"fruit",taste:"sour astringent",cuisines:["British","French","Scandinavian"],isJunk:false,junkReason:""},
  {name:"blackcurrant jam",category:"condiment",taste:"sweet sour",cuisines:["British","French"],isJunk:false,junkReason:""},
  {name:"blanched almond",category:"nut",taste:"sweet bitter",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"blanched almond flour",category:"grain",taste:"sweet bitter",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"blanched hazelnut",category:"nut",taste:"sweet bitter",cuisines:["French","Italian","Turkish"],isJunk:false,junkReason:""},
  {name:"blanched slivered almond",category:"nut",taste:"sweet bitter",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"blended oatmeal",category:"grain",taste:"sweet",cuisines:["American","British"],isJunk:false,junkReason:""},
  {name:"bleu cheese",category:"dairy",taste:"salty bitter pungent",cuisines:["French"],isJunk:false,junkReason:""},
  {name:"bleu cheese salad dressing",category:"condiment",taste:"salty sour",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"blood orange juice",category:"citrus",taste:"sour sweet",cuisines:["Italian","Spanish","Moroccan"],isJunk:false,junkReason:""},
  {name:"blue cheese",category:"dairy",taste:"salty bitter pungent",cuisines:["French","British","Italian"],isJunk:false,junkReason:""},
  {name:"blue cheese crumble",category:"dairy",taste:"salty bitter pungent",cuisines:["French","British"],isJunk:false,junkReason:""},
  {name:"blue cheese dressing",category:"condiment",taste:"salty sour pungent",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"blue cheese salad dressing",category:"condiment",taste:"salty sour pungent",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"blue curacao",category:"liqueur",taste:"sweet bitter",cuisines:["Caribbean","Dutch"],isJunk:false,junkReason:""},
  {name:"blueberrie",category:"fruit",taste:"sweet sour",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"blueberry",category:"fruit",taste:"sweet sour",cuisines:["American","Scandinavian"],isJunk:false,junkReason:""},
  {name:"blueberry jam",category:"condiment",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"blueberry juice",category:"liquid",taste:"sweet sour",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"blueberry preserve",category:"condiment",taste:"sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"blueberry sauce",category:"condiment",taste:"sweet sour",cuisines:["American","Scandinavian"],isJunk:false,junkReason:""},
  {name:"blueberry yogurt",category:"dairy",taste:"sour sweet",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"bluefish",category:"protein",taste:"umami",cuisines:["American","Turkish","Mediterranean"],isJunk:false,junkReason:""},
  {name:"bluefish fillet",category:"protein",taste:"umami",cuisines:["American","Turkish"],isJunk:false,junkReason:""},
  {name:"boiling chicken",category:"protein",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"boiling onion",category:"aromatic",taste:"pungent sweet",cuisines:["French","Italian","American"],isJunk:false,junkReason:""},
  {name:"boiling potato",category:"vegetable",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bolognese sauce",category:"condiment",taste:"umami salty sweet",cuisines:["Italian"],isJunk:false,junkReason:""},
  {name:"boned chicken",category:"protein",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"boneless beef",category:"protein",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"boneless beef chuck",category:"protein",taste:"umami",cuisines:["American","Argentine"],isJunk:false,junkReason:""},
  {name:"boneless beef chuck roast",category:"protein",taste:"umami",cuisines:["American","Argentine"],isJunk:false,junkReason:""},
  {name:"boneless beef round steak",category:"protein",taste:"umami",cuisines:["American","Argentine"],isJunk:false,junkReason:""}
];

const b04 = [
  {name:"boneless beef rump roast",category:"protein",taste:"umami",cuisines:["American","Argentine"],isJunk:false,junkReason:""},
  {name:"boneless beef short rib",category:"protein",taste:"umami",cuisines:["Argentine","Korean","American"],isJunk:false,junkReason:""},
  {name:"boneless beef sirloin",category:"protein",taste:"umami",cuisines:["Argentine","American"],isJunk:false,junkReason:""},
  {name:"boneless beef sirloin steak",category:"protein",taste:"umami",cuisines:["Argentine","American"],isJunk:false,junkReason:""},
  {name:"boneless lamb",category:"protein",taste:"umami",cuisines:["Australian","Greek","Turkish","Moroccan"],isJunk:false,junkReason:""},
  {name:"boneless pork",category:"protein",taste:"umami",cuisines:["Chinese","German","American"],isJunk:false,junkReason:""},
  {name:"boneless pork chop",category:"protein",taste:"umami",cuisines:["American","German"],isJunk:false,junkReason:""},
  {name:"boneless pork loin",category:"protein",taste:"umami",cuisines:["American","German","Chinese"],isJunk:false,junkReason:""},
  {name:"boneless skinless chicken breast",category:"protein",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bonito",category:"protein",taste:"umami salty",cuisines:["Japanese","Spanish"],isJunk:false,junkReason:""},
  {name:"bonito flakes",category:"umami",taste:"umami",cuisines:["Japanese"],isJunk:false,junkReason:""},
  {name:"borage",category:"herb",taste:"astringent bitter",cuisines:["Italian","Spanish","German"],isJunk:false,junkReason:""},
  {name:"borlotti bean",category:"protein",taste:"sweet umami",cuisines:["Italian"],isJunk:false,junkReason:""},
  {name:"bosc pear",category:"fruit",taste:"sweet",cuisines:["American","French"],isJunk:false,junkReason:""},
  {name:"boston lettuce",category:"vegetable",taste:"bitter astringent",cuisines:["American","French"],isJunk:false,junkReason:""},
  {name:"boston lettuce leave",category:"vegetable",taste:"bitter astringent",cuisines:["American","French"],isJunk:false,junkReason:""},
  {name:"botrytized wine",category:"liquid",taste:"sweet sour",cuisines:["French","German","Hungarian"],isJunk:false,junkReason:""},
  {name:"bouillon powder",category:"umami",taste:"umami salty",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bourbon",category:"spirit",taste:"sweet pungent",cuisines:["American","Southern US"],isJunk:false,junkReason:""},
  {name:"boursin cheese",category:"dairy",taste:"salty pungent",cuisines:["French"],isJunk:false,junkReason:""},
  {name:"bowtie pasta",category:"grain",taste:"sweet",cuisines:["Italian"],isJunk:false,junkReason:""},
  {name:"box wheat chex",category:"grain",taste:"sweet",cuisines:["American"],isJunk:true,junkReason:"Branded cereal product (Wheat Chex by General Mills)"},
  {name:"boysenberry",category:"fruit",taste:"sweet sour",cuisines:["American","Australian"],isJunk:false,junkReason:""},
  {name:"braeburn apple",category:"fruit",taste:"sweet sour",cuisines:["British","American"],isJunk:false,junkReason:""},
  {name:"bramley apple",category:"fruit",taste:"sour",cuisines:["British"],isJunk:false,junkReason:""},
  {name:"brandy",category:"spirit",taste:"sweet pungent",cuisines:["French","Spanish"],isJunk:false,junkReason:""},
  {name:"brandy flavoring",category:"condiment",taste:"sweet pungent",cuisines:["American","French"],isJunk:false,junkReason:""},
  {name:"brazil nut",category:"nut",taste:"sweet",cuisines:["Brazilian"],isJunk:false,junkReason:""},
  {name:"bread",category:"grain",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bread baguette",category:"grain",taste:"sweet",cuisines:["French"],isJunk:false,junkReason:""},
  {name:"bread crumb",category:"grain",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bread crumbs soft",category:"grain",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bread crust",category:"grain",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bread cube",category:"grain",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bread dough",category:"grain",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bread machine",category:"grain",taste:"sweet",cuisines:["Global"],isJunk:true,junkReason:"Appliance reference, not an ingredient"},
  {name:"bread machine yeast",category:"thickener",taste:"bitter pungent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bread mix",category:"grain",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bread pudding",category:"baked",taste:"sweet",cuisines:["British","American","French"],isJunk:true,junkReason:"Prepared dish, not a single ingredient"},
  {name:"bread roll",category:"grain",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"bread stuffing",category:"grain",taste:"sweet salty",cuisines:["American","British"],isJunk:false,junkReason:""},
  {name:"bread stuffing mix",category:"grain",taste:"sweet salty",cuisines:["American","British"],isJunk:false,junkReason:""},
  {name:"breadfruit",category:"vegetable",taste:"sweet",cuisines:["Pacific Islander","Caribbean","Filipino"],isJunk:false,junkReason:""},
  {name:"breading",category:"grain",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"breadnut tree seed",category:"nut",taste:"sweet",cuisines:["Caribbean","Pacific Islander"],isJunk:false,junkReason:""},
  {name:"breadstick",category:"baked",taste:"sweet salty",cuisines:["Italian","American"],isJunk:false,junkReason:""},
  {name:"breakfast cereal",category:"grain",taste:"sweet",cuisines:["American","British"],isJunk:false,junkReason:""},
  {name:"brick cheese",category:"dairy",taste:"salty umami",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"brie",category:"dairy",taste:"salty pungent umami",cuisines:["French"],isJunk:false,junkReason:""},
  {name:"brie cheese",category:"dairy",taste:"salty pungent umami",cuisines:["French"],isJunk:false,junkReason:""},
  {name:"brine",category:"liquid",taste:"salty",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"brisket of beef",category:"protein",taste:"umami salty",cuisines:["American","Jewish","Korean"],isJunk:false,junkReason:""},
  {name:"broad bean",category:"protein",taste:"sweet umami",cuisines:["Italian","Spanish","Lebanese","Egyptian"],isJunk:false,junkReason:""},
  {name:"broad noodle",category:"grain",taste:"sweet",cuisines:["Chinese","Vietnamese","Thai"],isJunk:false,junkReason:""},
  {name:"broccoli",category:"vegetable",taste:"bitter astringent",cuisines:["Italian","Chinese","American"],isJunk:false,junkReason:""},
  {name:"broccoli carrots cauliflower",category:"vegetable",taste:"bitter astringent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"broccoli cheese soup",category:"condiment",taste:"salty umami",cuisines:["American"],isJunk:true,junkReason:"Prepared compound soup product, not a single ingredient"},
  {name:"broccoli coleslaw",category:"vegetable",taste:"bitter astringent",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"broccoli crown",category:"vegetable",taste:"bitter astringent",cuisines:["American","Italian","Chinese"],isJunk:false,junkReason:""},
  {name:"broccoli cut",category:"vegetable",taste:"bitter astringent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"broccoli floret",category:"vegetable",taste:"bitter astringent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"broccoli floweret",category:"vegetable",taste:"bitter astringent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"broccoli flowerette",category:"vegetable",taste:"bitter astringent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"broccoli rabe",category:"vegetable",taste:"bitter astringent",cuisines:["Italian"],isJunk:false,junkReason:""},
  {name:"broccoli slaw",category:"vegetable",taste:"bitter astringent",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"broccoli slaw mix",category:"vegetable",taste:"bitter astringent",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"broccoli spear",category:"vegetable",taste:"bitter astringent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"broccoli stem",category:"vegetable",taste:"bitter astringent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"broccoli top",category:"vegetable",taste:"bitter astringent",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"broccolini",category:"vegetable",taste:"bitter astringent",cuisines:["Italian","American","Chinese"],isJunk:false,junkReason:""},
  {name:"broiler-fryer",category:"protein",taste:"umami",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"broiler-fryer chicken",category:"protein",taste:"umami",cuisines:["American"],isJunk:false,junkReason:""},
  {name:"broken nut meat",category:"nut",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"broth",category:"liquid",taste:"umami salty",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"broth from chicken",category:"liquid",taste:"umami salty",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"brown basmati rice",category:"grain",taste:"sweet",cuisines:["Indian","Pakistani"],isJunk:false,junkReason:""},
  {name:"brown bean",category:"protein",taste:"sweet umami",cuisines:["Dutch","Swedish"],isJunk:false,junkReason:""},
  {name:"brown bean sauce",category:"condiment",taste:"umami salty sweet",cuisines:["Chinese"],isJunk:false,junkReason:""},
  {name:"brown bread",category:"grain",taste:"sweet",cuisines:["British","German","Irish"],isJunk:false,junkReason:""},
  {name:"brown butter",category:"fat",taste:"sweet umami",cuisines:["French","Scandinavian","Indian"],isJunk:false,junkReason:""},
  {name:"brown button mushroom",category:"vegetable",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"brown chicken",category:"protein",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"brown egg",category:"protein",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"brown mushroom",category:"vegetable",taste:"umami",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"brown mustard",category:"condiment",taste:"pungent sour",cuisines:["American","German"],isJunk:false,junkReason:""},
  {name:"brown mustard seed",category:"spice",taste:"pungent bitter",cuisines:["Indian","Pakistani","Sri Lankan"],isJunk:false,junkReason:""},
  {name:"brown onion",category:"aromatic",taste:"pungent sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"brown potatoe",category:"vegetable",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"brown rice",category:"grain",taste:"sweet",cuisines:["Japanese","Korean","Thai","Global"],isJunk:false,junkReason:""},
  {name:"brown rice flour",category:"grain",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"brown rice syrup",category:"sweetener",taste:"sweet",cuisines:["Japanese","Korean"],isJunk:false,junkReason:""},
  {name:"brown rice vinegar",category:"acid",taste:"sour",cuisines:["Japanese","Chinese","Korean"],isJunk:false,junkReason:""},
  {name:"brown stock",category:"liquid",taste:"umami salty",cuisines:["French"],isJunk:false,junkReason:""},
  {name:"brown sugar",category:"sweetener",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"brown sugar substitute",category:"sweetener",taste:"sweet",cuisines:["Global"],isJunk:false,junkReason:""},
  {name:"brown vinegar",category:"acid",taste:"sour",cuisines:["British"],isJunk:false,junkReason:""},
  {name:"brunoise red pepper",category:"vegetable",taste:"sweet spicy",cuisines:["French","Spanish"],isJunk:false,junkReason:""},
  {name:"brussels sprout",category:"vegetable",taste:"bitter astringent",cuisines:["Belgian","French","British"],isJunk:false,junkReason:""},
  {name:"bryndza cheese",category:"dairy",taste:"salty sour pungent",cuisines:["Polish","Slovak","Hungarian"],isJunk:false,junkReason:""},
  {name:"bucatini pasta",category:"grain",taste:"sweet",cuisines:["Italian"],isJunk:false,junkReason:""}
];

fs.writeFileSync(path.join(__dirname, 'batch_01.out.json'), JSON.stringify(b01, null, 2));
fs.writeFileSync(path.join(__dirname, 'batch_02.out.json'), JSON.stringify(b02, null, 2));
fs.writeFileSync(path.join(__dirname, 'batch_03.out.json'), JSON.stringify(b03, null, 2));
fs.writeFileSync(path.join(__dirname, 'batch_04.out.json'), JSON.stringify(b04, null, 2));
console.log('b01:', b01.length, 'b02:', b02.length, 'b03:', b03.length, 'b04:', b04.length);
